/** UI copy */
export const copy = {
  home: {
    title: '40k XI Battles',
    tagline: 'Chapter Approved · Mission tracker',
    subtitle: 'Deathwatch kill-team scoring console',
    cta: 'New Game',
    activeGame: 'Resume Game',
    activeSub: 'Mission in progress',
    listsTitle: 'Detachments',
    listsDesc: '28 factions · 238 detachments',
    newGameWhileActive: 'Start new game anyway?',
    newGameWhileActiveBody:
      'This will replace your current mission in progress. Save or finish the active game first if you want to keep it.',
    resumeCta: 'Resume mission',
    rulesTitle: 'Rules',
    rulesDesc: '11th Edition reference',
    statsTitle: 'Record',
    statGames: 'Games',
    statWins: 'P1',
    statLosses: 'P2',
    statDraws: 'Draw',
    creditBy: 'by Big Pipe',
    credit: 'Unofficial · Not endorsed by Games Workshop',
    photoCredit: 'Hero art: Deathwatch theme',
  },
  nav: {
    home: 'Home',
    game: 'Game',
    backToGame: 'Back to game',
    lists: 'Detachment Points',
    rules: 'Rules',
    history: 'History',
  },
  newGame: {
    cancel: 'Cancel',
    title: 'New Game',
    back: 'Back',
    next: 'Continue',
    start: 'Start Game',
    layoutPick: 'Terrain layout variant',
    layoutPickHint: 'Chapter Approved recommends three terrain setups per matchup — agree or roll before deployment.',
  },
  game: {
    home: 'Home',
    abandon: 'Abandon',
    endGame: 'End Game',
    continue: 'Continue',
    save: 'Save to History',
    drawTactical: 'Draw 2 Cards',
    noTacticalCards: 'No cards in hand',
    returnToDeck: 'Return to Deck',
    returnToDeckHint: 'Shuffle back into the deck (round 1 redraw cards)',
    discardCard: 'Discard',
    removeFixed: 'Remove',
    firstPlayer: 'First turn',
    attacker: 'Attacker',
    defender: 'Defender',
    loading: 'Loading mission…',
    abandonTitle: 'Abandon mission?',
    abandonBody: 'Progress will be lost unless you save to history first.',
    rulesShortcut: 'Rules',
    mapShortcut: 'Map',
    deckRemaining: (n: number) => `${n} cards left`,
    primaryScoring: 'Primary Mission',
    secondaryScoring: 'Secondary Missions',
    roundVp: (n: number) => `Round ${n}`,
    prevRound: 'Previous Round',
    nextRound: 'Next Round',
    tabScore: 'Scoring',
    tabMission: 'Mission Brief',
    victoryPoints: 'Victory Points',
    wtcScore: 'WTC (20 pt)',
    wtcMargin: (n: number) => `Margin ${n} VP`,
    gameOver: 'Game Over',
    draw: 'Draw',
    wins: (name: string) => `${name} wins`,
    battleReady: 'Battle Ready',
    battleReadyBadge: 'Battle Ready +10 VP',
    battleReadyHint:
      'Army painted to Battle Ready standard (Chapter Approved Tournament Companion). +10 VP at end of game.',
    battleReadyOn: 'Painted to Battle Ready (+10 VP)',
    battleReadyOff: 'Not Battle Ready',
  },
  history: {
    empty: 'No games yet',
    emptyCta: 'Start a Game',
    delete: 'Delete',
    title: 'Game History',
    deleteConfirm: 'Delete this game from history?',
  },
  lists: {
    title: 'Detachment Points',
    search: 'Search armies or detachments…',
    dpLabel: 'Detachment Points',
    dpHint: 'Roster budget: 3 DP total · e.g. 3, or 2+1, or 1+1+1',
  },
  dp: {
    budget: 'Detachment Points',
    remaining: (n: number) => `${n} point${n === 1 ? '' : 's'} left`,
    full: 'Budget full',
    pickHint: 'Tap to add or remove · 3 DP max per army',
    tooMany: (cost: number, left: number) =>
      `Costs ${cost} DP · only ${left} left`,
  },
  rules: {
    title: 'Rules Reference',
  },
  battlefield: {
    title: 'Deployment & Terrain',
    matchupLabel: (id: number) => `Layout #${id}`,
    attacker: 'Attacker',
    defender: 'Defender',
    legend:
      'Red zone = Attacker deployment · Blue zone = Defender · Skulls = objectives · Grey footprints = terrain placement with suggested ruins.',
    setupTitle: 'Setup checklist',
    unavailableTitle: 'No map for this matchup',
    unavailableBody: (id: number) =>
      `Matchup #${id} has no digital terrain layout in the app yet. Pick a reference map below or use the Tournament Companion PDF.`,
    suggestedMaps: 'Maps you can use instead',
    suggestedHint: 'Same or similar Force Dispositions are listed first.',
    useReference: 'Use as reference',
    referenceBanner: (missionId: number, refId: number) =>
      `Reference layout #${refId} — your mission is still #${missionId}`,
    clearReference: 'Back to mission matchup',
    recommended: 'Best match',
    gwPdfLink: 'GW Tournament Companion PDF',
    gwTerrainTitle: 'Terrain footprints (11th Edition)',
    gwTerrainBody:
      'For missions using standard Strike Force deployment cards, pair the deployment map with one of eight recommended terrain layouts from the Tournament Companion.',
    gwTerrainKit: 'Standard area terrain kit',
    gwLayoutsTitle: 'GW Terrain Layouts 1–8',
    gwLayoutsHint: 'Which layouts suit each deployment mode (Tournament Companion mission pool):',
    flipToDefender: 'Flip so Defender is at the bottom of the screen',
    flipToAttacker: 'Flip so Attacker is at the top of the screen',
    viewAttackerTop: 'Attacker top',
    viewDefenderBottom: 'Defender bottom',
  },
  common: {
    close: 'Close',
    cancel: 'Cancel',
    confirm: 'Confirm',
    noResults: 'No matches',
    clearFilters: 'Clear filters',
  },
  wizard: {
    stepOf: (current: number, total: number) => `Step ${current + 1} of ${total}`,
  },
} as const
