/** UI copy */
export const copy = {
  home: {
    title: '40k XI Battles',
    tagline: 'Warhammer Event Companion · Mission tracker',
    subtitle: 'Deathwatch kill-team scoring console',
    cta: 'New Game',
    activeGame: 'Resume Game',
    activeSub: 'Mission in progress',
    listsTitle: 'Detachments',
    listsDesc: '28 factions · 265 detachments',
    armyListsTitle: 'Army Builder',
    armyListsKicker: 'Roster builder',
    armyListsDesc: '34 factions · WarOrgan 11th ed · detachments · enhancements · import/export',
    armyListsCta: 'Army Builder',
    armyListsBadge: '',
    tournamentListsTitle: 'Tournament lists',
    tournamentListsKicker: 'Competitive meta',
    tournamentListsDesc: 'Undefeated & X-1 lists from recent 16+ player events',
    newGameWhileActive: 'Start new game anyway?',
    newGameWhileActiveConfirm: 'Start anyway',
    newGameWhileActiveBody:
      'This will replace your current mission in progress. Save or finish the active game first if you want to keep it.',
    resumeCta: 'Resume mission',
    rulesTitle: 'Mission Sequence',
    rulesDesc: 'Event Companion v1.0 flow',
    statsTitle: 'Record',
    statGames: 'Games',
    statWins: 'Seat 1',
    statLosses: 'Seat 2',
    statDraws: 'Draw',
    creditBy: 'by Big Pipe',
    credit: 'Unofficial · Not endorsed by Games Workshop',
    photoCredit: 'Hero art: Deathwatch theme',
  },
  inDev: {
    title: 'In development',
    homeDesc: 'Early access modules — rough edges and rules gaps expected',
    body: 'These modules are early access — expect missing features, rough edges, and rules gaps vs the full Event Companions.',
    backHome: 'Back to Home',
  },
  formats: {
    sectionTitle: 'Other GW formats',
    sectionHint: 'Teams, Dominatus and Doubles Event Companions',
    teams: {
      title: 'Teams Match',
      subtitle: 'Team round BP totals · match TP result',
      badge: 'BP tracker',
    },
    dominatus: {
      title: 'Dominatus',
      subtitle: 'Dominatus Event Companion · campaign battles',
      body: 'Track Dominatus campaign battles with Agenda options, Alliance tags and post-battle card tallies.',
      phase: 'Campaign phase',
      location: 'Location',
      locationNotes: 'War zone rules / notes',
      players: 'Campaign players',
      playerName: 'Player name',
      addPlayer: 'Add',
      noPlayers: 'Add players to track Battle Honours, Battle Skills and Agenda Achieved cards.',
      bh: 'Battle Honour',
      bs: 'Battle Skill',
      aa: 'Agenda',
      postBattleTitle: 'After each battle',
      alliance: 'Alliance',
      attemptAgenda: 'Attempt Agenda',
      agendaName: 'Agenda name (optional)',
      locationStep: 'Location notes',
    },
    doubles: {
      title: 'Doubles',
      subtitle: '2v2 Event Companion · team scoring',
      body: 'Two players per team share one VP pool and take turns together.',
      teamName: 'Team name',
      player2: 'Player 2',
      army2: 'Second army (optional)',
      warlord: 'Warlord player',
    },
    comingSoon: 'Coming soon',
    pdfLink: 'Event Companion PDF',
    backHome: 'Back to Home',
    startDominatusBattle: 'Start Dominatus Battle',
    startDoublesBattle: 'Start Doubles Battle',
  },
  support: {
    title: 'Support the project',
    copy: 'Copy',
    copied: 'Copied',
    copyAria: 'Copy card number',
    hint: 'Card transfer · thank you!',
    feedback: 'Found a bug or have feedback? Email',
    email: 'wailance5921@gmail.com',
  },
  armyLists: {
    title: 'Army Builder',
    subtitle: 'Build matched-play lists from WarOrgan data',
    wipBadge: '',
    wipBody:
      'Points, detachments, enhancements and unit compositions from WarOrgan (Warhammer 40k 11th Edition v1.2). Duplicate-unit pricing tiers apply when adding the same unit again.',
    newList: 'New list',
    back: 'All lists',
    loading: 'Loading catalogue…',
    loadingDetachments: 'Loading detachments…',
    catalog: 'Unit catalogue',
    currentList: 'Your list',
    searchUnits: 'Search units, keywords, or max points…',
    searchLists: 'Search saved lists…',
    showLegends: 'Show Legends',
    addUnit: 'Add',
    addedUnit: (name: string) => `Added ${name}`,
    unitAtMaxCopies: (max: number) => `Maximum ${max} copies in this army`,
    removeUnit: 'Remove from list',
    deleteUnit: 'Delete',
    duplicateUnit: 'Duplicate',
    unitActions: 'Unit actions',
    unitInArmy: (count: number, max: number) => `${count}/${max} in army`,
    viewUnit: 'View datasheet',
    loadout: 'Loadout',
    loadoutHeading: 'Unit composition and wargear',
    selectionN: (n: number) => `Selection ${n}:`,
    mayHaveUpTo: (n: number) => `May have up to ${n} of these:`,
    selectOneOf: 'Select one of the following:',
    equippedWith: (gear: string[]) =>
      gear.length > 0 ? `equipped with: ${gear.join(' and ')}` : '',
    squadEquipped: (count: number, name: string, gear: string) =>
      `${count} ${name} equipped with: ${gear}`,
    squad: 'Squad',
    modelCount: 'Model count',
    models: 'models',
    noLoadoutOptions: 'No configurable wargear for this unit.',
    increaseLoadout: 'Increase',
    decreaseLoadout: 'Decrease',
    ranged: 'Ranged weapons',
    melee: 'Melee weapons',
    abilities: 'Abilities',
    empty: 'No saved lists yet',
    savedLists: 'Saved lists',
    emptyList: 'Add units from the catalogue',
    loadError: 'Could not load faction data. Try again later.',
    import: 'Import JSON',
    importError: 'Invalid roster file',
    importSuccess: 'List imported successfully',
    importSkipped: (count: number, names: string) =>
      count === 1
        ? `1 unit was skipped (not in catalogue): ${names}`
        : `${count} units were skipped (not in catalogue): ${names}`,
    exportJson: 'Export JSON',
    exportText: 'Copy list text',
    deleteConfirm: 'Delete this list?',
    detachmentsHint: (dpBudget: number) =>
      `11th Edition detachments (${dpBudget} DP budget)`,
    enhancementsHint: 'Enhancement names may differ from 11th Edition Chapter Approved',
    noEnhancements: 'No enhancements in this catalogue',
    tabCatalogue: 'Add units',
    tabArmy: 'My army',
    panelCatalog: 'Catalogue',
    panelRoster: 'Your army',
    catalogStep: 'Tap a unit to preview · use + to add',
    selectUnitHint: 'Pick a unit from the catalogue to preview its datasheet.',
    hideLegends: 'Hide Legends',
    bucketAll: 'All',
    bucketEpicHero: 'Epic Hero',
    bucketHero: 'Hero',
    bucketBattleline: 'Battleline',
    bucketTransport: 'Transport',
    bucketVehicle: 'Vehicle',
    bucketMounted: 'Mounted',
    bucketOther: 'Other',
    tabUnits: 'Units',
    tabDetachments: 'Detachments',
    tabEnhancements: 'Enhancements',
    stratagems: 'Stratagems',
    armyRules: 'Army rules',
    warlord: 'Warlord',
    leadUnit: 'Lead unit',
    noLeaderAttachment: 'Not attached',
    noEnhancement: 'No enhancement',
    noUpgrade: 'No upgrade',
    upgrades: 'Upgrades',
    importListFile: 'Import list file',
    exportListFile: 'Export list file',
    enhancementsPerUnit: 'Assign enhancements when editing a Character unit.',
    stepAllegiance: 'Step 1 · Allegiance',
    stepFaction: 'Step 2 · Faction',
    stepDetachment: 'Step 3 · Detachment',
    allegianceImperium: 'Imperium',
    allegianceChaos: 'Chaos',
    allegianceXenos: 'Xenos',
    allegianceAeldari: 'Aeldari',
    allegianceSpaceMarines: 'Space Marines',
    allegianceKnights: 'Knights',
    allegianceChaosDaemons: 'Chaos Daemons',
    allegianceHiveFleet: 'Hive Fleet',
    factionsCount: 'factions',
    codexChapters: 'Codex chapters',
    otherSpaceMarines: 'Chapter cults',
    changeAllegiance: 'Change allegiance',
    changeFaction: 'Change faction',
    changeDetachment: 'Change detachment',
    selectDetachment: 'Select detachment',
    detachmentSheetDetachments: 'Detachments',
    detachmentSheetReference: 'Rules & stratagems',
    detachmentTagBlocked: 'Conflicts with another selected detachment',
    startBuilding: 'Build army list',
    wizardPickDetachment: 'Select a detachment above to continue',
    unsavedUnitTitle: 'Discard changes?',
    unsavedUnitBody: 'You have unsaved edits to this unit.',
    discardChanges: 'Discard',
    showDatasheet: 'Show full datasheet',
    importList: 'Import list',
    searchListsLabel: 'Search lists',
    viewArmy: 'View army',
    backToCatalog: 'Add units',
    mobileDockSummary: (count: number, pts: number, limit: number) =>
      `${count} unit${count === 1 ? '' : 's'} · ${pts.toLocaleString()}/${limit.toLocaleString()} pts`,
    battleSizeLabel: 'Battle size',
    battleSizeIncursion: 'Incursion · 1,000 pts',
    battleSizeStrike: 'Strike Force · 2,000 pts',
    noDetachment: 'No detachment selected',
    detachmentDp: 'DP',
  },
  tournamentLists: {
    title: 'Tournament meta lists',
    subtitle: 'Recent undefeated and X-1 lists from 16+ player events',
    button: 'Tournament lists',
    loading: 'Loading tournament lists…',
    loadError: 'Could not load tournament lists. Try again later.',
    filterFaction: 'Filter by faction',
    allFactions: 'All factions',
    colName: 'Name',
    colFaction: 'Faction',
    colEvent: 'Event',
    colResult: 'Result',
    players: 'players',
    expand: 'Expand list',
    collapse: 'Collapse list',
    copyList: 'Copy list',
    copied: 'Copied',
    listUnavailable: 'List text not available for this entry.',
    empty: 'No lists match this filter.',
    prev: 'Previous',
    next: 'Next',
    listsShown: 'lists cached',
    updated: (date: string) => `Updated ${date}`,
  },
  nav: {
    home: 'Home',
    game: 'Game',
    backToGame: 'Back to game',
    armyLists: 'Army Builder',
    lists: 'Detachment Points',
    missionSequence: 'Mission Sequence',
    teamsBp: 'Teams BP',
    rules: 'Rules',
    history: 'History',
  },
  missionSequence: {
    title: 'Mission Sequence',
    subtitle: 'Warhammer Event Companion v1.0 · official 1v1 flow',
    pdfLink: 'Full PDF',
    terrainTitle: 'Create the battlefield',
    terrainHint: '44" × 60" table — three layouts (A/B/C) per Force Disposition pairing.',
    footprintsTitle: 'Recommended terrain footprints',
    terrainCta: 'Start a game to pick layout A/B/C for your matchup →',
    teamsLink: 'Teams Battle Points calculator',
  },
  newGame: {
    cancel: 'Cancel',
    title: 'New Game',
    titleDominatus: 'New Dominatus Battle',
    titleDoubles: 'New Doubles Battle',
    back: 'Back',
    next: 'Continue',
    start: 'Start Game',
    layoutPick: 'Terrain layout variant',
    layoutPickHint: 'Event Companion: three layouts (A/B/C) per matchup — agree or roll before deployment.',
    detachmentSwitch: 'Switch player',
    detachmentContinue: (name: string) => `Continue · ${name}`,
    detachmentBack: (name: string) => `Back · ${name}`,
    detachmentYourTurn: 'Your turn',
    tableSetup: 'Layout & confirm',
    tableSetupHint: 'Pick terrain layout A/B/C. Attacker and first turn are set at the table (Mission Sequence steps 8 & 10).',
    layoutPreBattleNote:
      'After Start Game, complete the pre-battle checklist in order before Round 1 scoring.',
    layoutPrimaryTitle: 'Primary missions',
    layoutPrimaryHint: 'Tap a mission name to read the card text before you deploy.',
    attackerLabel: 'Attacker',
    attackerHint: 'Defender sets up first (Mission Sequence step 8).',
    firstTurnLabel: 'First turn',
    firstTurnHint: 'Roll off — winner takes the first turn (step 10).',
    secondaryFixed: 'Fixed',
    secondaryFixedHint: 'Pick 2 of 4 · max 20 VP each',
    secondaryTactical: 'Tactical',
    secondaryTacticalHint: 'Draw in Command phase · max 40 VP game',
  },
  game: {
    home: 'Home',
    gameHeaderTitle: 'Live Battle',
    abandon: 'Abandon',
    endGame: 'End Game',
    continue: 'Continue',
    save: 'Save to History',
    drawTactical: 'Draw 1 Card',
    noTacticalCards: 'No cards in hand',
    returnToDeck: 'Return to deck',
    returnToDeckHint: 'Shuffle this card back into the deck',
    returnToDeckActionHint: 'Card leaves your hand · draw again with Random',
    discardCard: 'Discard',
    removeFixed: 'Remove',
    secondaryListTitle: 'Your secondaries',
    secondaryListFixedHint: 'Both fixed missions stay active for the whole battle.',
    secondaryListTacticalHint: 'Use Random or Manage to add cards to your hand. Manage also returns cards to deck or restores discarded.',
    secondaryStatusHand: 'In hand',
    secondaryStatusScored: 'Scored',
    secondaryStatusInactive: 'Off',
    secondaryStatusDiscarded: 'Discarded',
    secondaryHandFull: 'Hand is full — discard a card first',
    secondaryRestoreHint: 'Check to restore to hand',
    secondaryActivate: (card: string) => `Activate ${card}`,
    secondaryDeactivate: (card: string) => `Deactivate ${card}`,
    secondaryRestore: (card: string) => `Restore ${card} to hand`,
    secondaryPickerTitle: 'Secondary missions',
    secondaryPickerOpen: 'Manage',
    secondaryPickerRandom: 'Random',
    secondaryPickerSave: 'Apply',
    secondaryPickerEmpty: 'None selected',
    secondaryPickerDeck: 'In deck',
    secondaryPickerActive: 'Active',
    secondaryPickerFixedHint: 'Pick exactly 2 fixed secondaries.',
    secondaryPickerTacticalHint: 'Check deck cards to add to hand. Uncheck to return to deck. Discarded: Restore to deck.',
    secondaryPickerRestoreDeck: 'Restore to deck',
    secondaryPickerFixedCount: (n: number) => `Selected ${n}/2 — pick exactly 2`,
    secondaryPickerHandCount: (n: number) => `In hand: ${n}`,
    secondaryDiscard: 'Discard',
    secondaryDiscardCancel: 'Cancel',
    secondaryDiscardBanner: 'Tap a card — removes it and any scored VP for the rest of the battle',
    secondaryDiscardPick: 'Discard',
    secondaryPanelMeta: (deck: number, hand: number) => `${hand} in hand · ${deck} in deck`,
    secondaryPanelFixedMeta: (active: number, max: number) => `${active}/${max} active`,
    secondaryRandomBlockedFull: 'Deck empty',
    secondaryRandomBlockedEmpty: 'No missions available',
    secondaryDiscardBlocked: 'No missions to discard',
    secondaryDiscardBlockedFixed: 'Fixed missions cannot be discarded',
    secondaryScoreCheck: 'Mark scored',
    secondaryScoreUncheck: 'Unmark scored',
    firstPlayer: 'First turn',
    attacker: 'Attacker',
    defender: 'Defender',
    loading: 'Loading mission…',
    abandonTitle: 'Abandon mission?',
    abandonBody: 'Save to history to keep scores, or abandon to discard this game.',
    abandonSave: 'Save to History',
    scoringLockedPreBattle: 'Complete the pre-battle checklist before scoring.',
    scoringLockedPastRound: 'Past round — view only. Open the current round to score.',
    tacticalOnCurrentRound: 'Tactical cards are on the current round — tap › to go back.',
    advanceRound: (n: number) => `Start Round ${n}`,
    roundCurrent: (n: number) => `Scoring · R${n}`,
    roundViewing: (n: number) => `Viewing · R${n}`,
    noActiveGame: 'No active game',
    noActiveGameBody: 'Start a new game from Home or resume a saved mission.',
    playerSwitch: 'Player',
    tablePhaseTitle: 'Turn phase',
    tacticalHandTitle: 'Tactical cards',
    tacticalReturnDeck: 'Deck',
    tacticalDiscardCp: '+1 CP',
    tacticalRerollBtn: 'Reroll',
    mapShortcut: 'Map',
    rulesShortcut: 'Rules',
    deckRemaining: (n: number) => `${n} cards left`,
    primaryScoring: 'Primary Mission',
    secondaryScoring: 'Secondary Missions',
    roundVp: (n: number) => `Round ${n}`,
    roundVpThisRound: (n: number) => `This round: ${n} VP`,
    roundTab: (n: number) => `R${n}`,
    selectRound: 'Select battle round',
    roundPrev: (n: number) => `Previous · Round ${n}`,
    roundNext: (n: number) => `Next · Round ${n}`,
    roundShowResults: 'Results',
    prevRound: 'Prev',
    nextRound: 'Next',
    tabScore: 'Scoring',
    tabResults: 'Results',
    tabMission: 'Score Log',
    missionBriefOpen: 'Log',
    mapNoLayout: 'No terrain layout was selected for this game.',
    secondaryPickerRestoreBtn: 'Restore to deck',
    missionBriefDiscarded: 'Discarded',
    missionBriefAchieved: 'Achieved',
    missionBriefToggleShow: 'Show',
    missionBriefToggleHide: 'Hide',
    missionBriefRoundPrimary: 'Primary',
    missionBriefRoundSecondary: 'S',
    missionBriefNoVp: 'No VP scored yet',
    scoreStripHint: 'Tap player to switch scoring',
    scoreSeatScoring: 'Active player',
    scoreSeatSwitch: 'Tap to switch',
    roundSummaryTitle: (n: number) => `Round ${n} summary`,
    totalSummaryTitle: 'Match total',
    roundEmpty: 'No VP scored this round',
    discardForCp: 'Discard +1CP',
    discardForCpHint: 'End turn — discard this card for +1 CP (once per round)',
    rerollTactical: 'Reroll (1CP)',
    rerollTacticalHint: 'Once per battle at end of Command phase',
    rerollUsed: 'Reroll used',
    whenDrawnNote: 'When drawn',
    victoryPoints: 'Victory Points',
    wtcScore: 'WTC (20 pt)',
    wtcMargin: (n: number) => `Margin ${n} VP`,
    gameOver: 'Game Over',
    endGameSecondaryTitle: 'Secondary missions',
    endGameSecondaryEmpty: 'No secondaries scored',
    endGameSecondaryUncompleted: 'Not completed',
    endGameSecondaryRoundEmpty: 'No VP',
    formatDominatus: 'Dominatus',
    formatDoubles: 'Doubles 2v2',
    dominatusPostBattle: 'Dominatus post-battle',
    dominatusPostBattleHint: 'Check Agenda Achieved, then draw Battle Honour / Battle Skill per phase rules.',
    draw: 'Draw',
    wins: (name: string) => `${name} wins`,
    battleReady: 'Battle Ready',
    battleReadyBadge: 'Battle Ready +10 VP',
    battleReadyHint:
      'Army painted to Battle Ready standard (Warhammer Event Companion). +10 VP at end of game.',
    battleReadyOn: 'Painted to Battle Ready (+10 VP)',
    battleReadyOff: 'Not Battle Ready',
  },
  preBattle: {
    title: 'Pre-battle checklist',
    hint: 'Mission Sequence steps 7–11 in order. Set Attacker at step 8, First turn at step 10.',
    setAttacker: 'Attacker',
    setAttackerHint: 'Defender deploys first (step 8).',
    setFirstTurn: 'First turn',
    setFirstTurnHint: 'Record the roll-off winner (step 10).',
    readySummary: (attacker: string, firstTurn: string) =>
      `Ready · Attacker: ${attacker} · First turn: ${firstTurn}`,
  },
  cp: {
    title: 'Command Points',
    extraRemaining: (n: number) => `Extra CP this round: ${n}/1`,
    phase: (p: 'command' | 'turn' | 'end-turn') =>
      p === 'command' ? 'Command' : p === 'turn' ? 'Your turn' : 'End turn',
    hint: (p: 'command' | 'turn' | 'end-turn') => {
      if (p === 'command') {
        return 'Draw cards · Reroll one card (1 CP, once per battle).'
      }
      if (p === 'end-turn') {
        return 'Score secondaries · +1 CP discards one active card (once per round).'
      }
      return 'Play your turn.'
    },
    commandsFirst: (name: string) => `${name} commands first this round`,
  },
  teams: {
    title: 'Teams Battle Points',
    subtitle: 'Teams Event Companion — VP differential → BP',
    singleGame: 'Single game',
    player1Vp: 'Player / Team A VP',
    player2Vp: 'Opponent / Team B VP',
    addToRound: 'Add to team round',
    roundTotal: 'Team round total',
    teamSize: (n: number) => `${n}-player teams`,
    bpSum: (n: number) => `Combined BP for this game: ${n} (always 20)`,
    matchDraw: (tp: number) => `Match draw — each team ${tp} TP`,
    matchWin: (team: string, winTp: number, loseTp: number) =>
      `Team ${team} wins the match — ${winTp} TP vs ${loseTp} TP`,
    clearRound: 'Clear round',
    saveRound: 'Add round to match',
    newRound: 'New round',
    savedRounds: 'Round archive',
    teamAName: 'Team A name',
    teamBName: 'Team B name',
    savedAt: (iso: string) => new Date(iso).toLocaleString(),
    deleteRound: 'Delete',
    deleteRoundConfirm: 'Delete this saved team round?',
    activeRoundHint: 'Progress is saved automatically on this device.',
    matchTitle: 'Team match',
    matchHint: 'Each saved round adds Team Points to the running match total.',
    matchTp: (a: number, b: number) => `Match TP: ${a}–${b}`,
    finishMatch: 'Finish match',
    finishMatchConfirm: 'Save this match to history and start a new match?',
    savedMatches: 'Saved team matches',
    clearMatch: 'Reset match',
    roundInMatch: (n: number) => `Round ${n} in match`,
  },
  history: {
    empty: 'No games yet',
    emptyCta: 'Start a Game',
    delete: 'Delete',
    title: 'Game History',
    notFound: 'Game not found',
    back: 'Back to history',
    viewDetails: 'View breakdown',
    deleteConfirm: 'Delete this game from history?',
  },
  lists: {
    title: 'Detachment Points',
    search: 'Search armies or detachments…',
    dpLabel: 'Detachment Points',
    dpHint: 'Roster budget: 3 DP total · e.g. 3, or 2+1, or 1+1+1',
  },
  dp: {
    budget: 'Detachment Points',
    remaining: (n: number) => `${n} point${n === 1 ? '' : 's'} left`,
    full: 'Budget full',
    pickHint: 'Tap to add or remove · 3 DP max per army',
    tooMany: (cost: number, left: number) =>
      `Costs ${cost} DP · only ${left} left`,
  },
  rules: {
    title: 'Rules Reference',
  },
  battlefield: {
    title: 'Deployment & Terrain',
    matchupLabel: (id: number) => `Layout #${id}`,
    attacker: 'Attacker',
    defender: 'Defender',
    setupTitle: 'Setup checklist',
    flipToDefender: 'Flip so Defender is at the bottom of the screen',
    flipToAttacker: 'Flip so Attacker is at the top of the screen',
    viewAttackerTop: 'Attacker top',
    viewDefenderBottom: 'Defender bottom',
    previewNote: 'Attacker & defender are chosen at the table (Mission Sequence step 8).',
  },
  common: {
    close: 'Close',
    done: 'Done',
    save: 'Apply',
    cancel: 'Cancel',
    confirm: 'Confirm',
    noResults: 'No matches',
    clearFilters: 'Clear filters',
  },
  wizard: {
    stepOf: (current: number, total: number) => `Step ${current + 1} of ${total}`,
    progressLabel: 'Wizard progress',
    stepLabel: (name: string, n: number) => `Step ${n}: ${name}`,
  },
} as const
